name: My First Pipelines

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Print Welcome Message
        run: echo "Hello Sonu"

      - name: Show Date
        run: date

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la